apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zipkin
  annotations:
      kubernetes.io/ingress.class: "{{ .Values.ingress.class }}"
spec:
  rules:
  - host: {{ .Values.ingress.collector.host }}
    http:
      paths:
      - path: {{ .Values.ingress.collector.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.ingress.collector.serviceName }}
            port:
              number: {{ .Values.ingress.collector.servicePort }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zipkin-ui
  annotations:
      kubernetes.io/ingress.class: "{{ .Values.ingress.class }}"
spec:
  rules:
  - host: {{ .Values.ingress.ui.host }}
    http:
      paths:
      - path: {{ .Values.ingress.ui.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.ingress.ui.serviceName }}
            port:
              number: {{ .Values.ingress.ui.servicePort }}